swagger: '2.0'
info:
  version: 1.0.0
  title: 映画
  description: お気に入りの映画情報とまとめたAPI
paths:
  '/movies/{id}':
    get:
      description: 指定した映画情報を取得する
      parameters:
        - name: id
          in: path
          description: user id
          required: true
          type: number
      responses:
        '200':
          $ref: '#/responses/movie'
        '404':
          description: Not Found
          schema:
            type: object
            properties:
              result:
                $ref: ''
      operationId: reference
      summary: 映画情報取得
    parameters:
      - $ref: '#/parameters/id'
    put:
      summary: 映画情報更新
      operationId: update
      responses:
        '200':
          $ref: '#/responses/参照映画情報'
      description: 指定した映画情報を更新する
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/movie'
  /movie/:
    parameters: []
    post:
      summary: 映画情報登録
      operationId: regist
      responses:
        '200':
          description: OK
      description: 映画を登録する
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/movie'
  /movies/search:
    get:
      summary: 映画情報更新
      tags: []
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/movie'
      operationId: search
      parameters:
        - $ref: '#/parameters/name'
        - $ref: '#/parameters/opening_date'
      description: 映画を検索する
schemes:
  - https
produces:
  - application/json
basePath: movies
securityDefinitions: {}
responses:
  正常応答（映画情報あり）:
    description: Example response
    content:
      application/json:
        schema:
          properties:
            id:
              type: string
    schema:
      type: object
      properties:
        result:
          type: string
        '':
          $ref: '#/definitions/movies'
      required:
        - result
definitions:
  movie:
    title: movie
    type: object
    description: 映画情報
    x-examples: {}
    properties:
      name:
        type: string
        description: 映画名
      description:
        type: string
        description: 説明
      opening_date:
        type: string
        description: 公開日
        format: date
      director_name:
        type: string
        description: 監督名
    required:
      - name
      - description
      - opening_date
parameters:
  id:
    name: id
    in: path
    required: true
    schema:
      type: string
    description: 映画ID
  name:
    name: name
    in: query
    required: true
    schema:
      type: string
      maxLength: 200
    description: 映画名
  opening_date:
    name: opening_date
    in: query
    required: true
    schema:
      type: string
      format: date
    description: 公開日
host: 'localhost:8080'
